babel_key: c7db-7545-4c33-b2f8-1ebb1adfdfd3db80
data_to_process_path: E:/MyStuff/TFM/codigo/data/data_to_process_test.csv
dataset_is_lemmatized: false
id_list: []
lang: EN
lemma_list:
- "pulm\xF3n"
- cancer
- "respiraci\xF3n"
load_model_path: E:/MyStuff/TFM/codigo/model_saved
match_levenshtein_distance: 2
not_wait_when_token_are_spend: false
result_file_path: E:/MyStuff/TFM/grafical_results/result.json
save_html_view: E:/MyStuff/TFM/grafical_results/result.html
save_model_path: E:/MyStuff/TFM/grafical_results/model_saved
save_pattern_path: E:/MyStuff/TFM/grafical_results/pattern.json
search_levels: 2
tag_list: []
waiting_time_on_error: 300
