babel_key: asd
data_to_process_path: asd
dataset_is_lemmatized: false
id_list: []
lang: ES
lemma_list:
- asd
load_model_path: ''
match_levenshtein_distance: 2
not_wait_when_token_are_spend: false
result_file_path: asd/result.json
save_html_view: asd/result.html
save_model_path: asd/model_saved
save_pattern_path: asd/pattern.json
search_levels: 2
tag_list: []
waiting_time_on_error: 4000
